# Deploy on github pages

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: pre depçoy
        run: echo The PR was merged by ${{ github.actor }}

  then_builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - name: build
        with:
          node-version: '18'
        run: |
          corepack enable
          yarn
          yarn build

  then_sends_to_prod_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: 'dist'
          TARGET_BRANCH: 'prod'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch

