# Deploy on github pages

name: Deploy Github Pages

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: setup actions
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: build phase
        run: |
          corepack enable
          yarn
          yarn build

      - name: deploy phase
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist

