# Deploy on github pages

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: pre deploy
        run: echo The PR was merged by ${{ github.actor }}

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - name: then builds
        with:
          node-version: '18'
        run: corepack enable && yarn && yarn build

      - name: copy dist folder
        env:
          SRC_FOLDER_PATH: 'dist'
          TARGET_BRANCH: 'prod'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f)
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch
          git checkout $TARGET_BRANCH
          git checkout ${GITHUB_REF##*/} -- $files
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"
          git push origin $TARGET_BRANCH

