# Deploy on github pages

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: build
        run: |
          corepack enable
          yarn
          yarn build
      - name: copy dist
        uses: planetoftheweb/copy-to-branches@v1
        env:
          key: dev
          branches: prod
          files: dist
        #run: mv dist xSallus/boracodar-quiz-time/tree/prod

