# Deploy on github pages

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: |
          corepack enable
          yarn
          yarn build

  list_folders:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ls -la needs.build.outputs

